#!/usr/bin/env bash
#=============================================================================#
# Vonng's Environment Export
#   Author: vonng (fengruohang@outlook.com)
#=============================================================================#

#—————————————————————————————————————————————————————————————————————————————#
# Vim
# Make vim the default editor
export EDITOR="vim";
#—————————————————————————————————————————————————————————————————————————————#


#—————————————————————————————————————————————————————————————————————————————#
# Bash
# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768;
export HISTFILESIZE=$HISTSIZE;
export HISTCONTROL=ignoredups;
# Make some commands not show up in history
#export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help";
#—————————————————————————————————————————————————————————————————————————————#

#—————————————————————————————————————————————————————————————————————————————#
# Locale
# Prefer US English and use UTF-8
#export LANG="en_US.UTF-8";
#export LC_ALL="en_US.UTF-8";
#—————————————————————————————————————————————————————————————————————————————#

#—————————————————————————————————————————————————————————————————————————————#
# Man
# Highlight section titles in manual pages
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X";
#—————————————————————————————————————————————————————————————————————————————#

#—————————————————————————————————————————————————————————————————————————————#
# Grep
# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto";
#—————————————————————————————————————————————————————————————————————————————#


#—————————————————————————————————————————————————————————————————————————————#
# Maven
# MAVEN_OPTS='-Xms256m -Xmx512m'
#—————————————————————————————————————————————————————————————————————————————#

#—————————————————————————————————————————————————————————————————————————————#
# Node
# ES6 Compatible Mode
# NODE_ENV="development"
# NODE="`which node` --use-strict $(node --v8-options | grep harm | awk '{print $1}' | xargs)"
#—————————————————————————————————————————————————————————————————————————————#

