#!/usr/bin/env bash
#=============================================================================#
# Vonng's Extra bash settings
#   Author: vonng (fengruohang@outlook.com)
#=============================================================================#

#—————————————————————————————————————————————————————————————————————————————#
# Data Source
alias cnzzdb_dev="mysql -htddl.daily.alibaba.net -uCNZZDB_APP -p123456 -P3306"
alias up="cd %HOME/Dev;oss put elysium;"
alias cdv="cd /Volumes/Data//vserver"
alias cdpg="cd /usr/local/pgsql"
alias cdng="cd /usr/local/nginx"
#—————————————————————————————————————————————————————————————————————————————#

#—————————————————————————————————————————————————————————————————————————————#
# Data Source
alias cnzzdb_dev="mysql -htddl.daily.alibaba.net -uCNZZDB_APP -p123456 -P3306"
#—————————————————————————————————————————————————————————————————————————————#

#—————————————————————————————————————————————————————————————————————————————#
# Conf Edit shortcuts
alias virc='vim $HOME/.bashrc'
alias viprofile='vim $HOME/.bash_profile'
alias vipath='vim $HOME/.bash_inc/path'
alias viexport='vim $HOME/.bash_inc/export'
alias vialias='vim $HOME/.bash_inc/aliases'
alias vifunction='vim $HOME/.bash_inc/functions'
alias viextra='vim $HOME/.bash_inc/extra'
alias vissh='vim $HOME/.ssh/config'
alias vinginx="vim /usr/local/nginx/conf/nginx.conf"
alias vihost='vi /etc/hosts'
#—————————————————————————————————————————————————————————————————————————————#

#—————————————————————————————————————————————————————————————————————————————#
# Fast directories movement
alias cddev='cd $HOME/Dev'
alias cdgit='cd $HOME/Git'
alias cddown='cd $HOME/Downloads'
alias cdusr='cd $HOME/usr'
#—————————————————————————————————————————————————————————————————————————————#

#—————————————————————————————————————————————————————————————————————————————#
# Jupyter
alias qt="nohup jupyter qtconsole &"
#—————————————————————————————————————————————————————————————————————————————#

#—————————————————————————————————————————————————————————————————————————————#
# Taobao NPM
alias cnpm="npm --registry=https://registry.npm.taobao.org \
--cache=$HOME/.npm/.cache/cnpm \
--disturl=https://npm.taobao.org/dist \
--userconfig=$HOME/.cnpmrc"
#—————————————————————————————————————————————————————————————————————————————#
