#!/bin/sh
#=============================================================================#
# Vonng's Path
#   Author: Vonng (fengruohang@outlook.com)
#=============================================================================#

#—————————————————————————————————————————————————————————————————————————————#
# user's usr
MY_USR="${HOME}/usr"
MY_BIN="${MY_USR}/bin"
MY_CONF="${MY_USR}/conf"
MY_LOCAL="${MY_USR}/local"
MY_INCLUDE="${MY_USR}/include"
MY_LIB="${MY_USR}/lib"
MY_SCRIPT="${MY_USR}/script"
#—————————————————————————————————————————————————————————————————————————————#


#—————————————————————————————————————————————————————————————————————————————#
# Python
PYTHONHOME="/usr/local/anaconda";
PYTHONPATH="/usr/local/anaconda/lib";

export PYTHONHOME

# Tsinghua anaconda mirror
#conda config --add channels 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/'
#conda config --set show_channel_urls yes

# Tsinghua pip mirror
#pip install -i https://pypi.tuna.tsinghua.edu.cn/simple some-package

# Tsinghua pip mirror in ~/.pip/pip.conf
#[global]
#index-url = https://pypi.tuna.tsinghua.edu.cn/simple
#—————————————————————————————————————————————————————————————————————————————#


#—————————————————————————————————————————————————————————————————————————————#
# Java
JAVA_HOME=/usr/local/java
if [ "$(uname)" == "Darwin" ]; then
    JAVA_HOME=`/usr/libexec/java_home -v 1.8`
fi
CLASSPATH=".:${JAVA_HOME}/lib/dt.jar:${JAVA_HOME}/lib/tools.jar"

export CLASSPATH
export JAVA_HOME
#—————————————————————————————————————————————————————————————————————————————#


#—————————————————————————————————————————————————————————————————————————————#
# Go
GOROOT=/usr/local/go
GOPATH=$HOME/go

export GOROOT
export GOPATH
#—————————————————————————————————————————————————————————————————————————————#


#—————————————————————————————————————————————————————————————————————————————#
# Node
NODE_HOME=/usr/local/node

# TNPM
alias cnpm="npm --registry=https://registry.npm.taobao.org \
--cache=$HOME/.npm/.cache/cnpm \
--disturl=https://npm.taobao.org/dist \
--userconfig=$HOME/.cnpmrc"

#npm install tnpm --registry=http://registry.npm.alibaba-inc.com
#—————————————————————————————————————————————————————————————————————————————#


#—————————————————————————————————————————————————————————————————————————————#
# PostgreSQL
PGSQL_HOME="/usr/local/pgsql"
PGDATA="/var/pgsql/data"
PGCTL="${PGSQL_HOME}/bin/pg_ctl"

export PGDATA

alias pgstart="PYTHONPATH=${PYTHONPATH} ${PGCTL} start -D ${PGDATA} -l ${PGDATA}/log"
alias pgstop="${PGCTL} stop -D ${PGDATA}"
alias pgrestart="$PYTHONPATH=${PYTHONPATH} {PGCTL} restart -D ${PGDATA}"
alias pgreload="${PGCTL} reload"
alias vipgconf="vim ${PGDATA}/postgresql.conf"
alias vipghba="vim ${PGDATA}/pg_hba.conf"
#—————————————————————————————————————————————————————————————————————————————#


#—————————————————————————————————————————————————————————————————————————————#
# Nginx
NGINX_HOME="/usr/local/nginx"

alias ving="vi ${NGINX_HOME}/nginx.conf"
alias ngstart="${NGINX_HOME}/nginx"
alias ngreload="sudo ${NGINX_HOME}/nginx -s reload"
#—————————————————————————————————————————————————————————————————————————————#


#—————————————————————————————————————————————————————————————————————————————#
# Homebrew
# /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles
#—————————————————————————————————————————————————————————————————————————————#


#—————————————————————————————————————————————————————————————————————————————#
# PATH
PATH="${MY_BIN}:$PATH"
PATH="${PYTHONHOME}/bin:$PATH"
PATH="$PATH:${JAVA_HOME}/bin"
PATH="$PATH:${GOROOT}/bin:${GOPATH}/bin"
PATH="$PATH:${NODE_HOME}/bin"
PATH="$PATH:${PGSQL_HOME}/bin"
PATH="$PATH:${NGINX_HOME}/bin"

export PATH
#—————————————————————————————————————————————————————————————————————————————#