#!/usr/bin/env bash
#=============================================================================#
# Vonng's Path
#   Author: vonng (fengruohang@outlook.com)
#=============================================================================#

#—————————————————————————————————————————————————————————————————————————————#
# User's resource
MY_USR="$HOME/usr"
MY_BIN="$MY_USR/bin"
MY_CONF="$MY_USR/conf"
MY_LOCAL="$MY_USR/local"
MY_INCLUDE="$MY_USR/include"
MY_LIB="$MY_USR/lib"
MY_SCRIPT="$MY_USR/script"

PATH="$MY_BIN:$MY_SCRIPT:$PATH"
#—————————————————————————————————————————————————————————————————————————————#


#—————————————————————————————————————————————————————————————————————————————#
# Software
#-----------------------------#
# Python
ANACONDA_HOME="/usr/local/anaconda"
PATH="$ANACONDA_HOME/bin:$PATH"
PYTHONPATH=/usr/local/anaconda/lib/python2.7/site-packages/
#-----------------------------#
# Java
# JAVA_HOME=`/usr/libexec/java_home -v 1.8`
# MAVEN_HOME=/Users/vonng/usr/local/apache-maven-3.3.3
# M2_HOME=$MAVEN_HOME
# PATH="$JAVA_HOME/bin:$PATH"
#-----------------------------#
# Go
# GOROOT=/usr/local/go
# GOPATH=$HOME/Dev/Go
#-----------------------------#
# Node
# NODE_HOME=/usr/local/node
# PATH="$NODE_HOME/bin:$PATH"
#-----------------------------#
# PostgreSQL
PGSQL_HOME="/usr/local/pgsql"
PATH="$PGSQL_HOME/bin:$PATH"
#—————————————————————————————————————————————————————————————————————————————#

#—————————————————————————————————————————————————————————————————————————————#
# Export
export PATH
export PYTHONPATH
export MY_USR
export MY_SCRIPT
#—————————————————————————————————————————————————————————————————————————————#