#!/usr/bin/env bash
#=============================================================================#
# Vonng's private settings
#   Author: vonng (fengruohang@outlook.com)
#=============================================================================#


#=============================================================================#
# oss                                                                         #
#—————————————————————————————————————————————————————————————————————————————#
alias ols="oss ls"
alias orm="oss del"
alias ogt="oss get"
alias ogd="oss getd"
alias opt="oss put"

function ossgui()
{
    JRE_PATH=/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java
    OSS_PATH=/Users/vonng/usr/bin/ossbrowser.jar
    cd $HOME/usr/tmp
    $JRE_PATH -jar $OSS_PATH &
}
#—————————————————————————————————————————————————————————————————————————————#


#—————————————————————————————————————————————————————————————————————————————#
# Data Source
alias cnzzdb_dev="mysql -htddl.daily.alibaba.net -uCNZZDB_APP -p123456 -P3306"
alias cplusdb="psql -h 10.182.7.104 -p 3010"
export RDS="postgres://10.182.7.104:3010/cplus"
#—————————————————————————————————————————————————————————————————————————————#

