#!/usr/bin/env bash
#=============================================================================#
# Vonng's Bash Profile
#   Author: Vonng (fengruohang@outlook.com)
#=============================================================================#


#=============================================================================#
# Bash                                                                        #
#—————————————————————————————————————————————————————————————————————————————#
# Custome prompt for login shell
PROMPT_FILE="~/.bash_inc/prompt"
[ -r "${PROMPT_FILE}" ] && [ -f "${PROMPT_FILE}" ] && source "${PROMPT_FILE}";
unset PROMPT_FILE

# Bashrc for login/no-login shell
[[ -r ~/.bashrc ]] && . ~/.bashrc
#—————————————————————————————————————————————————————————————————————————————#
# History
export HISTSIZE=32768;
export HISTFILESIZE=$HISTSIZE;
export HISTCONTROL=ignoredups;
export HISTIGNORE="l:ls:cd:cd -:pwd:exit:date:* --help";    # Hide tedious cmd
#—————————————————————————————————————————————————————————————————————————————#
# Editor
export EDITOR="vim";
#—————————————————————————————————————————————————————————————————————————————#
# Locale
#export LANG="zh_CN.UTF-8";
#export LC_ALL="en_US.UTF-8";
#—————————————————————————————————————————————————————————————————————————————#
# Man
export LESS_TERMCAP_md="${yellow}";     #Highlight man page title
export MANPAGER="less -X";
#=============================================================================#


#=============================================================================#
# Bash Opt                                                                    #
#—————————————————————————————————————————————————————————————————————————————#
shopt -s nocaseglob;    # case-insensitive globbing
shopt -s histappend;    # append rather than overwrite in bash history
shopt -s cdspell;       # auto-correct typos in cd
for option in autocd globstar; do
    shopt -s "$option" 2> /dev/null;
done;                   # Bash 4 features
#=============================================================================#


#=============================================================================#
# Completion                                                                  #
#—————————————————————————————————————————————————————————————————————————————#
# Git completion
if type _git &> /dev/null && [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
    complete -o default -o nospace -F _git g;
fi;
#—————————————————————————————————————————————————————————————————————————————#
# SSH hostname from `~/.ssh/config`
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2 | tr ' ' '\n')" scp sftp ssh;
#—————————————————————————————————————————————————————————————————————————————#
# Tab completion for `defaults read|write NSGlobalDomain`
complete -W "NSGlobalDomain" defaults;
#—————————————————————————————————————————————————————————————————————————————#
# `killall` tab completion for common apps
complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal Twitter" killall;
#=============================================================================#