#!/bin/sh
#=============================================================================#
# Vonng's bash setup script
#   Author: Vonng (fengruohang@outlook.com)
#=============================================================================#

#—————————————————————————————————————————————————————————————————————————————#
# Locate
dirname $0 | grep "^/" >/dev/null
if [ $? -eq 0 ]; then
  # Absolute path
  cd $(dirname $0);
else
  # Relative path
  cd $(dirname $(pwd)/$0);
fi

SRC_HOME=`pwd`;
#—————————————————————————————————————————————————————————————————————————————#

#—————————————————————————————————————————————————————————————————————————————#
# Copy config file
for file in bash{rc,_inc,_profile}; do
    rm -rf "${HOME}/.${file}" && cp -r "${SRC_HOME}/${file}" "${HOME}/.${file}";
done;

file="~/.bashrc"
[ -r "$file" ] && [ -f "$file" ] && source "$file";
unset file;
echo "bash done"
#—————————————————————————————————————————————————————————————————————————————#